### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ahmedelashker** [Esri/map-northarrow-ios#1]
[UIImageView setMapViewForNorthArrow:]: unrecognized selector sent to instance

I tried putting the set mapView for imageView in mapViewDidLoad, it loads the map and the imageView but then it crashes again

**Comment by nixta** [comment]
If it's not recognizing setMapViewForNorthArrow:, it's possible that the target for `UIImageView+AGSNorthArrow.m` has not been set? Make sure it's the output of your project.

Are you able to run the demo project?

If you're still having trouble, please post the full stack trace of the error.

**Comment by nixta** [comment]
@ahmedelashker Let me know if this is still not working for you and I'll reopen.

**Comment by ahmedelashker** [comment]
Thanks for your support nixta and sorry to feedback late, the demo project runs successfully and however I tried following your steps more than once it just kept crashing. Eventually I was frustrated enough to do the following:

1- Copy the addObserver and addTapGesture code
2- Copy the handleGesture method
3- Copy the setNorthArrowAngle method
4- Copy the KVO method
5- Manually adjust the layout constraints for the image view.

And then it finally worked.

Thanks again.

**Comment by nixta** [comment]
If you have the broken project and want me to take a look I'd be happy to. Can't promise anything but I'll have a quick look.

**Comment by ahmedelashker** [comment]
I don't have the older version now actually, but I shortly tried to roll it back and it's not crashing now with the .h and .m files. However you should still mention the layout constraining part for the image view within the xib as it doesn't rotate around it's origin.

**Comment by nixta** [comment]
Or I could fix the project :) I'll open a new issue.
